PedidosOnline/Models/Actividad.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Actividad
{

    public int RowID { get; set; }

    public Nullable<int> TipoID { get; set; }

    public string Tema { get; set; }

    public Nullable<int> PrioridadID { get; set; }

    public Nullable<int> EstadoID { get; set; }

    public string Descripcion { get; set; }

    public System.DateTime FechaInicial { get; set; }

    public System.DateTime FechaFinal { get; set; }

    public Nullable<int> TerceroERPID { get; set; }

    public Nullable<int> ContactoID { get; set; }

    public Nullable<int> TipoRelacionID { get; set; }

    public string UsuarioCreacion { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }



    public virtual Opcion Opcion { get; set; }

    public virtual Opcion Opcion1 { get; set; }

    public virtual Tercero Tercero { get; set; }

    public virtual Opcion Opcion2 { get; set; }

    public virtual Contacto Contacto { get; set; }

    public virtual Opcion Opcion3 { get; set; }

}

}

PedidosOnline/Models/Contacto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Contacto
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Contacto()
    {

        this.Actividad = new HashSet<Actividad>();

        this.TerceroPotencial = new HashSet<TerceroPotencial>();

    }


    public int RowID { get; set; }

    public string Nombre { get; set; }

    public string Identificacion { get; set; }

    public string Apellido { get; set; }

    public string Direccion1 { get; set; }

    public string Direccion2 { get; set; }

    public string Direccion3 { get; set; }

    public string Telefono1 { get; set; }

    public string Telefono2 { get; set; }

    public string Fax { get; set; }

    public string CodigoPostal { get; set; }

    public Nullable<int> CiudadID { get; set; }

    public string Email { get; set; }

    public string Skype { get; set; }

    public string Descripcion { get; set; }

    public string ruta_imagen { get; set; }

    public string Celular { get; set; }

    public string Cargo { get; set; }

    public string Area { get; set; }

    public Nullable<int> SucursalID { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public string UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public string UsuarioModificacion { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Actividad> Actividad { get; set; }

    public virtual Ciudad Ciudad { get; set; }

    public virtual Sucursal Sucursal { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TerceroPotencial> TerceroPotencial { get; set; }

}

}

PedidosOnline/Controllers/CRMController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PedidosOnline.Models;
using PedidosOnline.Utilidades;
using System.IO;
namespace PedidosOnline.Controllers
{
    public class CRMController : Controller
    {
        PedidosOnlineEntities db = new PedidosOnlineEntities();

        #region :::::METODOS GENERALES:::::
        private FormCollection DeSerialize(FormCollection FormData)
        {
            FormCollection collection = new FormCollection();
            //un-encode, and add spaces back in
            string querystring = Uri.UnescapeDataString(FormData["FormData"]).Replace("+", " ");
            var split = querystring.Split(new[] { '&' }, StringSplitOptions.RemoveEmptyEntries);
            Dictionary<string, string> items = new Dictionary<string, string>();
            foreach (string s in split)
            {
                string text = s.Substring(0, s.IndexOf("="));
                string value = s.Substring(s.IndexOf("=") + 1);

                if (items.Keys.Contains(text))
                    items[text] = items[text] + "," + value;
                else
                    items.Add(text, value);
            }
            foreach (var i in items)
            {
                collection.Add(i.Key, i.Value);
            }
            return collection;
        }
        public JsonResult Get_Ruta_File()
        {

            try
            {
                HttpPostedFileBase file = Request.Files[0];

                var ruta = "";
                if (file != null && file.ContentLength > 0)
                {
                    string Guid_Img = Guid.NewGuid().ToString();
                    Guid_Img = Guid_Img.Substring(1, 7);
                    var nombreArchivo = Guid_Img.Trim() + "_" + Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Recurso/ImagenPerfil"), nombreArchivo);

                    ruta = "/Recurso/ImagenPerfil/" + nombreArchivo;
                    try
                    {
                        Directory.CreateDirectory(Server.MapPath("~/Recurso/ImagenPerfil"));
                    }
                    catch (Exception ex) { }
                    file.SaveAs(path);
                }

                if (string.IsNullOrEmpty(ruta))
                {
                    Response.StatusCode = 500;
                    return Json("No hay archivo adjunto");
                }
                return Json(ruta);
            }
            catch { }

            Response.StatusCode = 500;
            return Json("No hay archivo adjunto");
        }

        public string SelectPaises()
        {
            string result = "<option value=''>-Seleccionar-</option>";
            foreach (var item in db.Pais.ToList())
            {
                result += "<option value='" + item.RowID + "'>" + item.Nombre + "</option>";
            }
            return result;
        }
        public string SelectDepartamento(int? rowid)
        {
            string result = "<option value=''>-Seleccionar-</option>";
            foreach (var item in db.Departamento.Where(f => f.PaisID == rowid).ToList())
            {
                result += "<option value='" + item.RowID + "'>" + item.Nombre + "</option>";
            }
            return result;
        }
        public string SelectCiudades(int? rowid)
        {
            string result = "<option value=''>-Seleccionar-</option>";
            foreach (var item in db.Ciudad.Where(f => f.DepartamentoID == rowid).ToList())
            {
                result += "<option value='" + item.RowID + "'>" + item.Nombre + "</option>";
            }
            return result;
        }
        #endregion

        #region :::::ERP TERCERO:::::
        [CheckSessionOut]
        public ActionResult ListadoTercerosSucursal()
        {
            ViewBag.listercero = db.Tercero.ToList();
            return View();
        }
        [CheckSessionOut]
        public ActionResult Tercero(int rowid_tercero)
        {
            //todos los contactos
            ViewBag.ListadoContactos = db.Contacto.ToList();


            //los combos
            //ViewBag.Tipos_Industria = _db.m_metaclasses.Where(f => f.class_code == "TERCERO.TIPO.INDUSTRIA").ToList();
            ViewBag.Tipos_Industria = db.Opcion.Where(f => f.Agrupacion.Nombre == "TERCERO.TIPO.INDUSTRIA").ToList();
            //ViewBag.Clasificacion = _db.m_metaclasses.Where(f => f.class_code == "TERCERO.CLASIFICACION").ToList();
            //ViewBag.Clasificacion = db.Opcion.Where(f => f.Agrupacion.Nombre == "TERCERO.CLASIFICACION").ToList();

            //usuario actual
            //var usuario = ((usuario)Session["NombreUsuario"]).nombre_usuario;
            var usuario = ((Usuario)Session["curUser"]).NombreUsuario;

            //el tercero a observar
            //var tercero = _db.erp_terceros.Where(f => f.rowid == rowid_tercero).FirstOrDefault();
            var tercero = db.Tercero.Where(f => f.RowID == rowid_tercero).FirstOrDefault();

            //actividades del tercero.
            ViewBag.ListaActividades = db.Actividad.Where(f => f.TerceroERPID == tercero.RowID).ToList();
            //ViewBag.ListaActividades = _db.crm_actividades.Where(f => f.rowid_relacion == tercero.rowid).OrderByDescending(f => f.fecha_creacion).ToList();

            //puntos de envio del tercero
            ViewBag.ListadoPuntoEnv = db.PuntoEnvio.Where(f => f.VendedorID == tercero.RowID).ToList();

            ContactoERP cp;
            //sucursales del tercero
            ViewBag.ListadoSucursales = db.Sucursal.Where(f => f.TerceroID == rowid_tercero).ToList();


            try
            {
                cp = db.ContactoERP.Where(f => f.RowID == tercero.ContactoERPID).First();
            }
            catch (Exception e)
            { cp = new ContactoERP(); }


            TerceroCompletInfo tcrm = new TerceroCompletInfo();
            tcrm.tercero = db.Tercero.Where(f => f.RowID == rowid_tercero).FirstOrDefault();
            tcrm.contacto_principal = cp;


            //tcrm.contacto_principal = cp;
            #region Pedidos - Diarios
            //List<t_pedido> ListaPedidos_ValorGrafica = new List<t_pedido>();


            //if (UtilTool.ObtenerParametro("USAR_DATOS_ERP_QUEMADOS") == "T")
            //{
            //    ListaPedidos_ValorGrafica = _db.t_pedido
            //            .Where(f => f.fecha_pedido >= DateTime.Today.AddDays(-30))
            //            .OrderBy(f => f.fecha_pedido).ToList();
            //}
            //else
            //{
            //    ListaPedidos_ValorGrafica = _db.t_pedido
            //            .Where(f => f.numpedido_erp != null && f.numpedido_erp != "" && f.erp_terceros_sucursale.rowid_tercero == rowid_tercero)
            //            .Where(f => f.fecha_pedido >= DateTime.Today.AddDays(-30))
            //            .OrderBy(f => f.fecha_pedido).ToList();
            //}

            //List<DatoValorGrafica> listaDias = ListaPedidos_ValorGrafica.GroupBy(f => f.fecha_pedido).Select(group => new DatoValorGrafica
            //{
            //    Dato = "", 
            //    Valor = Math.Round(group.Sum(f => f.valor_total), 0),
            //    DatoFecha = group.Key
            //}).ToList();

            List<DatoValorGrafica> listaDiasFinal = new List<DatoValorGrafica>();

            //int z = 1;
            //for (int i = -30; i <= 0; i++)
            //{
            //    DateTime curFecha = DateTime.Today.AddDays(i);
            //    DatoValorGrafica curDato = listaDias.Where(f => f.DatoFecha == curFecha).FirstOrDefault();

            //    if (curDato == null)
            //        curDato = new DatoValorGrafica
            //        {
            //            Dato = (curFecha.Day == 1 || i == -30) ? curFecha.ToString("MMM/dd") : curFecha.ToString("dd"),
            //            Valor = 0,
            //            DatoFecha = curFecha,
            //            Seq = z++,
            //        };
            //    else
            //    {
            //        curDato.Dato = (curFecha.Day == 1 || i == -30) ? curFecha.ToString("MMM/dd") : curFecha.ToString("dd");
            //        curDato.Seq = z++;
            //    }

            //    listaDiasFinal.Add(curDato);
            //}


            ViewBag.listaPedidos = listaDiasFinal;

            #endregion

            #region Pedidos - Mensuales
            //List<t_pedido> ListaPedidos_ValorGrafica_M = new List<t_pedido>();
            //if (UtilTool.ObtenerParametro("USAR_DATOS_ERP_QUEMADOS") == "T")
            //{
            //    ListaPedidos_ValorGrafica_M = _db.t_pedido
            //            .Where(f => f.fecha_pedido >= DateTime.Today.AddMonths(-11).AddDays(-1 * DateTime.Today.Day + 1))
            //            .OrderBy(f => f.fecha_pedido).ToList();
            //}
            //else
            //{
            //    ListaPedidos_ValorGrafica_M = _db.t_pedido
            //            .Where(f => f.fecha_pedido >= DateTime.Today.AddMonths(-11).AddDays(-1 * DateTime.Today.Day + 1))
            //            .Where(f => f.numpedido_erp != null && f.numpedido_erp != "" && f.erp_terceros_sucursale.rowid_tercero== rowid_tercero)
            //            .OrderBy(f => f.fecha_pedido).ToList();
            //}
            //List<DatoValorGrafica> listaMes = ListaPedidos_ValorGrafica_M.GroupBy(f => f.fecha_pedido.Month)
            //            .Select(group => new DatoValorGrafica
            //            {
            //                Dato = "",
            //                Valor = Math.Round(group.Sum(f => f.valor_total), 0),
            //                DatoFecha = group.Min(f => f.fecha_pedido)

PedidosOnline/Views/CRM/ListadoActividades.cshtml
@model IEnumerable<PedidosOnline.Models.Actividad>
@{
    ViewBag.Title = "ListadoActividades";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/js/select2/select2.css" rel="stylesheet" />
<script type="text/javascript" src="~/js/select2/select2.min.js?v=166"></script> <!-- Styled select boxes -->

<script>
    $(document).ready(function () {

        $('table').dataTable({
            " processing": true,
            "bFilter": true,
            "bPaginate": true,
            "info": false,
            "bDestroy": true,
            aLengthMenu: [
            [11, 25, 50, 100, -1],
            [11, 25, 50, 100, "All"]
            ],
            "iDisplayLength": 11
        });
    });

    function ExportarExcel() {//permite exportar desde el data procedure con la palabra clave
        UtilExportarExcel('ACTIVIDADES', $("#table_filter").find("input").val());
    }
</script>

<div class="nav">
    <span>
        <a href="@Url.Action( "Actividad","CRM",new { @rih=Request.Params["rih"] })" style="text-decoration: none; color: black; font-size: 12px; ">
            <i class="glyphicon glyphicon-plus"></i>&nbsp;Nuevo
        </a>
    </span>
    <span>
        &nbsp;&nbsp;
        <a href="javascript:ExportarExcel();" class="alink">
            <i class="glyphicon glyphicon-export"></i>&nbsp;<span class="lang" key="EXPORTAR">Exportar</span>
        </a>
    </span>
</div>
<br />
<div class="row ">
    <div class="col-md-12">
        <table id="table" class="table table-condensed table-striped table-bordered table-hover table-checkable table-responsive">
            <thead>
                <tr>
                    <th></th>
                    <th class="lang" key="TIPO">Tipo</th>
                    <th class="lang" key="ASUNTO">Asunto</th>
                    <th class="lang" key="PRIORIDAD">Prioridad</th>
                    <th class="lang" key="TIPO_REFERENCIA">Tipo Referencia</th>
                    <th class="lang" key="REFERENCIADO_A">Referenciado a</th>
                    <th class="lang" key="DESCRIPCION">Descripción</th>
                    <th class="lang" key="INICIO">Inicio</th>
                    <th class="lang" key="FIN">Fin</th>
                    <th class="lang" key="ESTADO">Estado</th>
                    <th class="lang" key="USUARIO_CREACION">Usuario</th>
                </tr>
            </thead>
            <tbody>


                @foreach (PedidosOnline.Models.Actividad actividad in ((List<PedidosOnline.Models.Actividad>)@Model).ToList())
                {
                    if (actividad.Contacto==null)
                    {
                        actividad.Contacto = new PedidosOnline.Models.Contacto();
                    }
                    if (actividad.Tercero==null)
                    {
                        actividad.Tercero = new PedidosOnline.Models.Tercero();
                    }
                    <tr>
                        <td>
                            <!--Se debe descomentar cuando se cree la tabla contacto-->
                            <a href="@Url.Action("Actividad", "CRM", new { @rowid = @actividad.RowID,   @rih = Request.Params["rih"]   })"><i class="glyphicon glyphicon-pencil"> </i></a>
                        </td>
                        <td>
                            @actividad.Opcion2.Nombre  @*opcion*@
                        </td>
                        <td>
                            @actividad.Tema
                        </td>
                        <td>
                            @actividad.Opcion1.Nombre @*opcion*@
                        </td>
                        <td>
                            @actividad.Opcion3.Nombre
                        </td>
                        @*<td>
                                @actividad.Tercero.NombreComercial   @actividad.Contacto.Nombres @actividad.Contacto.Apellidos
                            </td>*@
                        <td>
                            @if (actividad.TerceroERPID != null)
                            {
                                @actividad.Tercero.RazonSocial

                            }
                            else if (actividad.ContactoID != null)
                            {
                                @actividad.Contacto.Apellido

                            }
                        </td>
                        <td>
                            @actividad.Descripcion
                        </td>
                        <td>
                            @actividad.FechaInicial
                        </td>
                        <td>
                            @actividad.FechaFinal
                        </td>
                        <td>
                            @actividad.Opcion2.Nombre @*opcion*@
                        </td>
                        <td>
                            @actividad.UsuarioCreacion
                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

PedidosOnline/Views/CRM/ListadoContactos.cshtml
@model IEnumerable<PedidosOnline.Models.Contacto>
@{
    ViewBag.Title = "ListadoContacto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/js/select2/select2.css" rel="stylesheet" />
<script type="text/javascript" src="~/js/select2/select2.min.js?v=166"></script> <!-- Styled select boxes -->
<script>
    $(document).ready(function () {
        $('table').dataTable({
            " processing": true,
            "bFilter": true,
            "bPaginate": true,
            "info": false,
            "bDestroy": true,
            aLengthMenu: [
            [11, 25, 50, 100, -1],
            [11, 25, 50, 100, "All"]
            ],
            "iDisplayLength": 11

        });

    });
    function ExportarExcel() {//permite exportar desde el data procedure con la palabra clave
        UtilExportarExcel('CONTACTOS', $("#table_filter").find("input").val());
    }
</script>

<div class="nav">
    <span>
        <a href="@Url.Action( "Contacto","CRM",new { @rih=Request.Params["rih"] })" class="alink">
            <i class="glyphicon glyphicon-plus"></i>&nbsp;Nuevo
        </a>
    </span>
    <span>
        &nbsp;&nbsp;
        <a href="javascript:ExportarExcel();" class="alink">
            <i class="glyphicon glyphicon-export"></i>&nbsp;<span class="lang alink" key="EXPORTAR">Exportar</span>
        </a>
    </span>
</div>
<br />

<div class="row ">
    <div class="col-md-12">
        <table id="table" class="table table-condensed table-striped table-bordered table-hover table-checkable table-responsive">
            <thead>
                <tr>
                    <th></th>
                    <th class="lang" key="IDENTIFICACION">Identificación</th>
                    <th class="lang" key="SUCURSAL">Sucursal</th>
                    <th class="lang" key="NOMBRES">Nombres</th>
                    <th class="lang" key="APELLIDOS">Apellidos</th>
                    <th class="lang" key="CORREO">Correo</th>
                    <th class="lang" key="TELEFONO">Teléfono</th>
                    <th class="lang" key="CELULAR">Celular</th>
                    <th class="lang" key="CARGO">Cargo</th>
                    <th class="lang" key="AREA">Area</th>
                    @*<th class="lang" key="FECHA_CREACION">Fecha Creación</th>*@
                </tr>
            </thead>
            <tbody>

                @foreach (PedidosOnline.Models.Contacto contacto in @Model.ToList())
                {
                    <tr>
                        <td>
                            <a href="@Url.Action("Contacto", "CRM", new { @rowid = @contacto.RowID,   @rih = Request.Params["rih"]   })"><i class="glyphicon glyphicon-pencil"> </i></a>
                        </td>
                        <td>
                            @contacto.Identificacion
                        </td>
                        <td>
                            @*@if (contacto.SucursalID != null) {
                                    @contacto.Sucursales.NombreSucursal
                                }*@
                        </td>
                        <td>
                            @contacto.Nombre
                        </td>
                        <td>
                            @contacto.Apellido
                        </td>
                        <td>
                            <a href="mailto:@contacto.Email">@contacto.Email</a>
                        </td>
                        <td>
                            @contacto.Telefono1
                        </td>
                        <td>
                            @contacto.Celular
                        </td>
                        <td>
                            @contacto.Cargo
                        </td>
                        <td>
                            @contacto.Area
                        </td>
                        @*<td>
                                @contacto.fecha_creacion
                            </td>*@
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

PedidosOnline/Views/CRM/ListadoPotenciales.cshtml
@model IEnumerable<PedidosOnline.Models.TerceroPotencial>
@{
    ViewBag.Title = "Listado_Potenciales";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>

    $(document).ready(function () {
        $('table').dataTable({
            " processing": true,
            "bFilter": true,
            "bPaginate": true,
            "info": false,
            "bDestroy": true,
            aLengthMenu: [
            [11, 25, 50, 100, -1],
            [11, 25, 50, 100, "All"]
            ],
            "iDisplayLength": 11

        });

    });
    function ExportarExcel() {//permite exportar desde el data procedure con la palabra clave
        UtilExportarExcel('CLI.POTENCIALES', $("#DataTables_Table_0_wrapper").find("input").val());
    }
</script>
<div class="nav">
    <span>
        <a href="@Url.Action( "Cliente_Nuevo","CRM",new {@nm="Nuevo Cliente", @rih=Request.Params["rih"] })" class="alink" style="z-index:99999999;">
            <i class="glyphicon glyphicon-plus"></i>&nbsp;<span class="lang" key="NUEVO">Nuevo</span>
        </a>
    </span>
    <span>
        &nbsp;&nbsp;
        <a href="javascript:ExportarExcel();" class="alink">
            <i class="glyphicon glyphicon-export"></i>&nbsp;<span class="lang" key="EXPORTAR">Exportar</span>
        </a>
    </span>
</div>
<br />
<div class="row ">
    <div class="col-md-12">
        <table class="table table-condensed table-striped table-bordered table-hover table-checkable table-responsive" style="margin-right:20px;">
            <thead>
                <tr>
                    <th></th>
                    <th class="lang" key="RAZON_SOCIAL">Razon Social</th>
                    <th class="lang" key="ID">ID</th>
                    <th class="lang" key="ESTADO">Estado</th>
                    <th class="lang" key="TEL_EMPRESA">Tel. Empresa</th>
                    <th class="lang" key="CONTACTO">Contacto</th>
                    <th class="lang" key="CELULAR">Celular</th>
                    <th class="lang" key="EMAIL">Email</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.ToList() != null)
                {<!--Esto me lo imprime en pantalla porque el if no tiene el aroa, pero si lo pongo me imprime error-->
                    foreach (var potencial in @Model.ToList())
                    {
                        potencial.Contacto = potencial.Contacto != null ? potencial.Contacto : new PedidosOnline.Models.Contacto();
                        <tr>
                            <td>
                                <a href="@Url.Action("Cliente_Nuevo", "CRM", new { @rowid = @potencial.RowID,@nm="Modificar Cliente", @rih=Request.Params["rih"] })"><i class="glyphicon glyphicon-pencil"> </i></a>
                            </td>
                            <td>
                                @potencial.RazonSocial
                            </td>
                            <td>
                                @potencial.Identificacion
                            </td>
                            <td>
                                @if (potencial.Opcion != null)
                                {
                                    @potencial.Opcion.Nombre
                                }
                            </td>
                            <td>
                                @potencial.Contacto.Telefono1
                            </td>
                            <td>
                                @potencial.Contacto.Nombre @potencial.Contacto.Apellido
                            </td>
                            <td>
                                @potencial.Contacto.Telefono2
                            </td>
                            <td>
                                <a href="mailto:@potencial.Contacto.Email">@potencial.Contacto.Email</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>

PedidosOnline/Views/CRM/ListadoTercerosSucursal.cshtml
@{
    ViewBag.Title = "Listado_TercerosSucursal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/js/select2/select2.css" rel="stylesheet" />
<script type="text/javascript" src="~/js/select2/select2.min.js?v=166"></script> <!-- Styled select boxes -->
<script>

    $(document).ready(function () {
        $('table').dataTable({
            " processing": true,
            "bFilter": true,
            "bPaginate": true,
            "info": false,
            "bDestroy": true,
            aLengthMenu: [
            [15, 25, 50, 100, -1],
            [15, 25, 50, 100, "All"]
            ],
            "iDisplayLength": 15

        });

    });
    function ExportarExcel() {//permite exportar desde el data procedure con la palabra clave
        UtilExportarExcel('TERCEROS', $("#table_filter").find("input").val());
    }
</script>

<div class="nav">

    <span>
        <a href="javascript:ExportarExcel();" class="alink">
            <i class="glyphicon glyphicon-export"></i>&nbsp;<span class="lang" key="EXPORTAR">Exportar</span>
        </a>
    </span>
</div>
<br />

<div class="row ">
    <div class="col-md-12">
        <table id="table" class="table table-condensed table-striped table-bordered table-hover table-checkable table-responsive">
            <thead>
                <tr>
                    <th></th>
                    <th class="lang" key="NIT">Nit</th>
                    <th class="lang" key="RAZON SOCIAL">Razon Social</th>
                    <th class="lang" key="CONTACTO_PRINCIPAL">Contacto Principal</th>
                    <th class="lang" key="TELEFONO">Telélefono</th>
                    <th class="lang" key="TIPO_RELACION">Tipo de Relación</th>
                    <th class="lang" key="COMERCIAL">Comercial</th>
                </tr>
            </thead>
            <tbody>
                @if (ViewBag.listercero != null)
                {<!--Esto me lo imprime en pantalla porque el if no tiene el aroa, pero si lo pongo me imprime error-->
                    foreach (PedidosOnline.Models.Tercero item in ViewBag.listercero)
                    {
                        string tipo_relacion = "";
                        item.ContactoERP = item.ContactoERP == null ? new PedidosOnline.Models.ContactoERP() : item.ContactoERP;
                        <tr>
                            <td>
                                <a href="@Url.Action("Tercero", "CRM", new { @rowid_tercero = @item.RowID, @rih = Request.Params["rih"] })"><i class="glyphicon glyphicon-search"> </i></a>
                            </td>
                            <td>
                                @item.Identificacion
                            </td>
                            <td>
                                @item.RazonSocial
                            </td>
                            <td>
                                @item.ContactoERP.Nombre
                            </td>
                            <td>
                                @item.ContactoERP.Telefono1
                            </td>
                            <td>
                                @if (item.Cliente == 1)
                                { tipo_relacion = "Cliente "; }
                                @if (item.Proveedor == 1)
                                {
                                    if (tipo_relacion.Length > 0)
                                    { tipo_relacion += ","; }
                                    tipo_relacion += " Proveedor ";
                                }
                                @if (item.Accionista == 1)
                                {
                                    if (tipo_relacion.Length > 0)
                                    { tipo_relacion += ","; }
                                    tipo_relacion += " Socio ";
                                }
                                @tipo_relacion
                            </td>
                            <td>
                                @item.NombreComercial
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>