PedidosOnline/Models/Booking.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Booking
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Booking()
    {

        this.EncabezadoMatrizBL = new HashSet<EncabezadoMatrizBL>();

    }


    public int RowID { get; set; }

    public Nullable<int> ProformaID { get; set; }

    public Nullable<int> TipoLlenadoID { get; set; }

    public string Nota { get; set; }

    public string Asunto { get; set; }

    public string CorreoEnvio { get; set; }



    public virtual Proforma Proforma { get; set; }

    public virtual Opcion Opcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EncabezadoMatrizBL> EncabezadoMatrizBL { get; set; }

}

}

PedidosOnline/Models/Calculadora.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Calculadora
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Calculadora()
    {

        this.CalculadoraItems = new HashSet<CalculadoraItems>();

        this.Contrato = new HashSet<Contrato>();

    }


    public int RowID { get; set; }

    public Nullable<int> TerceroID { get; set; }

    public Nullable<int> AgenteNavieraID { get; set; }

    public Nullable<int> DestinoID { get; set; }

    public System.DateTime Fecha { get; set; }

    public string observacion { get; set; }

    public Nullable<int> IncotermID { get; set; }

    public string UsuarioCreacion { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public bool Terminada { get; set; }

    public Nullable<int> BrokerID { get; set; }



    public virtual AgenteNaviera AgenteNaviera { get; set; }

    public virtual AgenteNaviera AgenteNaviera1 { get; set; }

    public virtual Ciudad Ciudad { get; set; }

    public virtual Tercero Tercero { get; set; }

    public virtual Tercero Tercero1 { get; set; }

    public virtual Tercero Tercero2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CalculadoraItems> CalculadoraItems { get; set; }

    public virtual Opcion Opcion { get; set; }

    public virtual Opcion Opcion1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Contrato> Contrato { get; set; }

}

}

PedidosOnline/Models/Contrato.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Contrato
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Contrato()
    {

        this.ContratoAdjunto = new HashSet<ContratoAdjunto>();

        this.OrdenCompraContrato = new HashSet<OrdenCompraContrato>();

        this.OrdenCompraContrato1 = new HashSet<OrdenCompraContrato>();

        this.Proforma = new HashSet<Proforma>();

    }


    public int RowID { get; set; }

    public Nullable<int> IntermediarioID { get; set; }

    public Nullable<int> ClienteID { get; set; }

    public Nullable<int> VendedorID { get; set; }

    public Nullable<int> InspectorID { get; set; }

    public Nullable<int> CalculadoraID { get; set; }

    public Nullable<int> TipoContratoID { get; set; }

    public string Calidad1 { get; set; }

    public string Calidad2 { get; set; }

    public string TerminosCondiciones { get; set; }

    public Nullable<System.DateTime> Fecha { get; set; }

    public Nullable<bool> Seguro { get; set; }

    public Nullable<System.DateTime> Periodo { get; set; }

    public Nullable<bool> EmbarqueParcial { get; set; }

    public Nullable<int> UsuarioCreacionID { get; set; }

    public string Consecutivo { get; set; }

    public Nullable<System.DateTime> FechaCreacion { get; set; }

    public Nullable<int> UsuarioActualizaID { get; set; }

    public Nullable<System.DateTime> FechaActualizacion { get; set; }

    public string Transporte { get; set; }

    public Nullable<int> FormaPagoID { get; set; }



    public virtual Tercero Tercero { get; set; }

    public virtual Tercero Tercero1 { get; set; }

    public virtual Tercero Tercero2 { get; set; }

    public virtual Tercero Tercero3 { get; set; }

    public virtual Calculadora Calculadora { get; set; }

    public virtual Opcion Opcion { get; set; }

    public virtual Opcion Opcion1 { get; set; }

    public virtual Usuario Usuario { get; set; }

    public virtual Usuario Usuario1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ContratoAdjunto> ContratoAdjunto { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrdenCompraContrato> OrdenCompraContrato { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrdenCompraContrato> OrdenCompraContrato1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Proforma> Proforma { get; set; }

}

}

PedidosOnline/Controllers/ExportacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PedidosOnline.Models;
using System.Data.SqlClient;
using System.IO;
using PedidosOnline.Utilidades;

namespace PedidosOnline.Controllers
{
    public class ExportacionController : Controller
    {
        PedidosOnlineEntities db = new PedidosOnlineEntities();
        //GET: Exportacion
        #region ::::::METODOS GENERALES::::::
        private FormCollection DeSerialize(FormCollection FormData)
        {
            FormCollection collection = new FormCollection();
            //un-encode, and add spaces back in
            string querystring = Uri.UnescapeDataString(FormData[0]).Replace("+", " ");
            var split = querystring.Split(new[] { '&' }, StringSplitOptions.RemoveEmptyEntries);
            Dictionary<string, string> items = new Dictionary<string, string>();
            foreach (string s in split)
            {
                string text = s.Substring(0, s.IndexOf("="));
                string value = s.Substring(s.IndexOf("=") + 1);

                if (items.Keys.Contains(text))
                    items[text] = items[text] + "," + value;
                else
                    items.Add(text, value);
            }
            foreach (var i in items)
            {
                collection.Add(i.Key, i.Value);
            }
            return collection;
        }
        public JsonResult Buscar_Tercero()
        {
            List<Terceros> data = new List<Terceros>();
            string terms = Request.Params["term"].Trim().ToUpper();
            List<Terceros> Lista = (from listado in db.Tercero
                                    where (listado.RazonSocial.Contains(terms))
                                    select new Terceros()
                                    {
                                        RowID = listado.RowID,
                                        RazonSocial = listado.RazonSocial,
                                        label = listado.RazonSocial,


                                    }).Distinct().OrderBy(f => f.label).ToList();//.Take(15);
            data.AddRange(Lista.ToList());


            var jsonResult = Json(data.OrderBy(f => f.RowID), JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }
        public JsonResult Buscar_Tercero_Proveedor()
        {
            List<Terceros> data = new List<Terceros>();
            string terms = Request.Params["term"].Trim().ToUpper();
            List<Terceros> Lista = (from listado in db.Tercero
                                    where (listado.RazonSocial.Contains(terms) && listado.Proveedor == 1)
                                    select new Terceros()
                                    {
                                        RowID = listado.RowID,
                                        RazonSocial = listado.RazonSocial,
                                        label = listado.RazonSocial,


                                    }).Distinct().OrderBy(f => f.label).ToList();//.Take(15);
            data.AddRange(Lista.ToList());


            var jsonResult = Json(data.OrderBy(f => f.RowID), JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }
        public JsonResult Buscar_Calculadora()
        {
            List<Terceros> data = new List<Terceros>();
            string terms = Request.Params["term"].Trim().ToUpper();
            var ListaCalc = (from listado in db.Calculadora.Where(listado => listado.Tercero.RazonSocial.Contains(terms) || listado.Tercero.Identificacion.Contains(terms))
                             select new
                             {
                                 RowID = listado.RowID,
                                 Fecha = listado.Fecha,
                                 IdentificacionTercero = listado.Tercero.Identificacion,
                                 label = string.Concat(listado.Tercero.Identificacion + " ", listado.Tercero.RazonSocial, " ", listado.Opcion.Nombre),
                                 Contacto = listado.Tercero.ContactoERP.Nombre,
                                 ContactoTelefono = listado.Tercero.ContactoERP.Telefono1,
                                 RowIDCliente = listado.Tercero.RowID,
                                 incoterm = listado.Opcion.Nombre,
                                 tranportecorresponde = listado.Opcion.Codigo
                             }).Distinct().OrderBy(cal => cal.RowID).ToList();
            var returnjson = Json(ListaCalc.OrderBy(cal => cal.RowID), JsonRequestBehavior.AllowGet);
            returnjson.MaxJsonLength = int.MaxValue;
            return returnjson;
        }

        public JsonResult Buscar_Empresa()
        {
            List<Terceros> data = new List<Terceros>();
            string terms = "INDUTRADE".ToUpper();
            var ListaCalc = (from listado in db.Tercero.Where(listado => listado.RazonSocial.Contains(terms))
                             select new
                             {
                                 RowID = listado.RowID,
                                 IdentificacionTercero = listado.Identificacion,
                                 label = string.Concat(listado.Identificacion + " ", listado.RazonSocial),
                             }).Distinct().OrderBy(cal => cal.RowID).ToList();
            var returnjson = Json(ListaCalc.OrderBy(cal => cal.RowID), JsonRequestBehavior.AllowGet);
            returnjson.MaxJsonLength = int.MaxValue;
            return returnjson;
        }
        public JsonResult ItemsAutocomplete()
        {
            string term = Request.Params["term"];

            try
            {
                var data = (from item in db.Item
                                                 .Where(f => f.Descripcion.Contains(term)
                                                 || f.Referencia.Contains(term.Trim())).ToList()
                            select new
                            {
                                embalaje = item.Unidad,
                                rowid = item.RowID,
                                nombre = item.Referencia + " " + item.Descripcion,
                                label = item.Referencia + " " + item.Descripcion
                            }).Distinct().OrderBy(f => f.label).Take(15);
                return Json(data, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }
        
        #endregion

        #region:::::CONTRATO:::::
        public string EliminarEvidenciaContrato(int? rowid)
        {
            db.ContratoAdjunto.Remove(db.ContratoAdjunto.Where(f => f.RowID == rowid).FirstOrDefault());
            db.SaveChanges();
            return "";
        }
        [CheckSessionOut]
        public string CargarEvidenciasContrato(int? rowid)
        {
            string result = "";
            foreach (var item in db.ContratoAdjunto.Where(f => f.ContratoID == rowid).ToList())
            {
                result += "<tr><td><a href=\"" + item.Recurso + "\" target=\"_blank\"><i class=\"glyphicon glyphicon-picture\"></i></a></td><td>" + item.Descripcion + "</td><td>" + item.UsuarioCreacion + "</td><td>" + item.FechaCreacion + "</td><td><a onclick=\"EliminarEvidencia(" + item.RowID + ")\"><i class=\"glyphicon glyphicon-trash\"></a></td></tr>";
            }

            return result;
        }
        [CheckSessionOut]
        public string ContratoAdjuntoGuardar()
        {
            try
            {
                HttpPostedFileBase file = Request.Files[0];
                int? rowid = int.Parse(Request.Params["rowid"]);
                var ruta = "";
                if (file != null && file.ContentLength > 0)
                {
                    string Guid_Img = Guid.NewGuid().ToString();
                    Guid_Img = Guid_Img.Substring(1, 7);
                    var nombreArchivo = Guid_Img.Trim() + "_" + Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/RepositorioArchivos/ArchivosContrato"), nombreArchivo);
                    //Directory.CreateDirectory(path);

                    ruta = "/RepositorioArchivos/ArchivosContrato/" + nombreArchivo;
                    try
                    {
                        Directory.CreateDirectory(Server.MapPath("~/RepositorioArchivos/ArchivosContrato"));
                    }
                    catch (Exception ex) { }
                    file.SaveAs(path);
                    ContratoAdjunto contratoad = new ContratoAdjunto();
                    contratoad.Recurso = ruta;
                    contratoad.ContratoID = rowid;
                    contratoad.Descripcion = Request.Params["descripcion"];
                    contratoad.UsuarioCreacion = ((Usuario)Session["curUser"]).NombreUsuario;
                    contratoad.FechaCreacion = DateTime.Now;
                    db.ContratoAdjunto.Add(contratoad);
                    db.SaveChanges();

                }

                if (string.IsNullOrEmpty(ruta))
                {
                    Response.StatusCode = 500;
                }
            }
            catch (Exception e)
            {
                Response.StatusCode = 500;
            }

            return "";
        }
        [CheckSessionOut]
        public ActionResult Contrato(int? rowid)
        {
            Models.Contrato contrato = new Models.Contrato();
            ViewBag.Termino = db.m_plantillas.Where(mp => mp.Nombre == "TERMINOSCONTRATO").FirstOrDefault();

PedidosOnline/Views/Exportacion/CertificadoCalidad.cshtml
@model PedidosOnline.Models.CertificadoCalidad
@{
    ViewBag.Title = "CertificadoCalidad";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/Tabs.css" rel="stylesheet" />
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=2.0, maximum-scale=1.0, minimum-scale=1.0">
<script type="text/javascript" src="~/Content/js/datetimepicker/jquery.datetimepicker.full.min.js"></script>
<link href="~/Content/js/datetimepicker/jquery.datetimepicker.css" rel="stylesheet">
<script>
    $(document).ready(function () {
        $('.calendario').datepicker({
            dateFormat: 'dd/mm/yy',
            minDate: 0,
            maxDate: '+3Y',
            inline: true
        });

        $('.solo-numero').keyup(function () {
            this.value = (this.value + '').replace(/[^0-9]/g, '');
        });

        $("#documentobl").autocomplete({
            source: "Buscar_MatricesBL",
            minLenght: 1,
            select: function (evento, ui) {//seleccion al autocompletar
                debugger
                if (ui.item != null) {//si hay valor en la seleccion autocompletar
                    $("#documentobl").val(ui.item.Label);
                    $("#documento_mtz").val(ui.item.RowID);
                    $("#cliente").val(ui.item.expedidor);
                }
            },
            change: function (event, ui) {

            }
        });

        $('#producto').autocomplete({
            source: "Buscar_Producto",
            minLength: 1,
            select: function (evento, ui) {
                debugger
                $('#producto').val(ui.item.label);
                $('#producto_id').val(ui.item.rowid);
            }
        });

    });

    function guardar_certificado_calidad(accion) {
        $.ajax({
            type: "POST",
            url: "/CertificadoCalidad/guardar_certificado",
            data: {
                formulario: $("#formPrincial").serialize(),
                Rowid_certificado: $("#rowid").val()
            },
            success: function (data2) {
                if(a == 1){
                    if (@Model.RowID >0) {
                        Mensajes('Guardado Satisfactoriamente','success','');
                    }
                    else
                    {
                        location.href="../Contrato/Contrato?rowid="+data2;
                    }
                    ModalProcesandoHiden();
                }
                else
                {
                    location.href="../Contrato/Contratos";
                }
            },
            error: function (request) {
                Mensajes(request.responseText, 'error', '');
                ModalProcesandoHiden();
            }
        });
    }

</script>
<div class="row">
    <div class="row" id="div_menu" style="margin-bottom:20px">
        <div class="col-md-12">
            <div class="nav">
                <span>
                    &nbsp;&nbsp;
                    <a href="@Url.Action("ListaCertificadoCalidad","Exportacion",new {  @rih = Request.Params["rih"] })" class="alink">
                        <i class="glyphicon glyphicon-list-alt"></i>&nbsp;<span class="lang" key="VISTA">Vista</span>
                    </a>
                </span>
                &nbsp;&nbsp;
                <span>
                    <a href="javascript:guardar_certificado_calidad(1);" class="alink">
                        <i class="glyphicon glyphicon-floppy-disk"></i>&nbsp;<span class="lang" key="GUARDAR">Guardar</span>
                    </a>
                </span>
                <span>
                    &nbsp;&nbsp;
                    <a href="javascript:Guardar(2);" class="alink">
                        <i class="glyphicon glyphicon-floppy-disk"></i><span class="lang" key="GUARDAR_&_CERRAR">&nbsp;Guardar&nbsp;&&nbsp;Cerrar</span>
                    </a>
                </span>
            </div>
        </div>
    </div>
    <div class="tabbable tabbable-custom tabs-top">
        <ul class="nav nav-tabs tabs-top">
            <li class="active"><a href="#tab_1" id="litab_1" data-toggle="tab" class="lang" key=""> Certificado de calidad</a></li>
        </ul>
    </div>
    <div class="tab-content" style="overflow:hidden">
        <div class="tab-pane active" id="tab_1">
            <div class="col-md-8" style="margin-top:20px;">
                <form id="formPrincial" name="formPrincial" method="post" onsubmit="return false">
                    <input type="hidden" name="rowid" id="rowid" value="@Model.RowID" />
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-3">
                                <label class="lang">Fecha Revisi&oacute;n </label>
                            </div>
                            <div class="col-md-6">
                                <input class="calendario" type="text" id="fecha_revision" name="fecha_revision" value="@Model.FechaRevision" style="width:100%" placeholder="---" readonly />
                            </div>
                        </div>
                        <br />
                        <div class="row">
                            <div class="col-md-3">
                                <label class="lang">Documento BL</label>
                            </div>
                            <div class="col-md-6">
                                <input type="text" id="documentobl" name="documentobl" style="width:100%" placeholder="---" />
                                <input type="hidden" id="documento_mtz" style="width:100%" name="documento_mtz" value="@Model.MatrizBLID" />
                            </div>
                        </div>
                        <br />
                        <div class="row">
                            <div class="col-md-3">
                                <label class="lang">Cliente</label>
                            </div>
                            <div class="col-md-6">
                                <input type="text" id="cliente" name="cliente" style="width:100%" placeholder="---" readonly disabled />
                            </div>
                        </div>
                        <br />
                        <div class="row">
                            <div class="col-md-3">
                                <label class="lang">Ciudad</label>
                            </div>
                            <div class="col-md-6">
                                <select style="width:100%" id="ciudad" name="ciudad">
                                    <option value="">- Seleccionr -</option>
                                    @foreach (PedidosOnline.Models.Ciudad ciudad in ViewBag.listaciudades)
                                    {
                                        <option value="@ciudad.RowID">@ciudad.Nombre</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <br />
                        <div class="row">
                            <div class="col-md-3">
                                <label class="lang">Direcci&oacute;n</label>
                            </div>
                            <div class="col-md-6">
                                <textarea style="resize:none; width:100%" name="direccion" value="@Model.Direccion" id="direccion"></textarea>
                            </div>
                        </div>
                        <br />
                        <div class="row">
                            <div class="col-md-3">
                                <label class="lang">Producto</label>
                            </div>
                            <div class="col-md-6">
                                <input type="text" name="producto" style="width:100%" id="producto" />
                                <input type="hidden" name="producto_id" id="producto_id" value="@Model.ProductoID" />
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-3">
                                <label class="lang">Cantidad</label>
                            </div>
                            <div class="col-md-6">
                                <input type="number" id="cantidad" style="width:30%" name="cantidad" value="@Model.Cantidad" />
                            </div>
                        </div>
                        <br />
                        <div class="row">
                            <div class="col-md-3">
                                <label class="lang">Codigo</label>
                            </div>
                            <div class="col-md-6">
                                <input type="text" class="solo-numero" id="codigo" style="width:100%" name="codigo" value="@Model.Codigo" />
                            </div>
                        </div>
                        <br />
                        <div class="row">
                            <div class="col-md-3">
                                <label class="lang">Fecha Elaboracion Producto</label>
                            </div>
                            <div class="col-md-6">
                                <input class="calendario" type="text" id="fecha_elaboracion" name="fecha_elaboracion" placeholder="---" style="width:100%" @Model.Fecha_Elaboracion_Producto readonly />
                            </div>
                        </div>
                        <br />
                        <div class="row">
                            <div class="col-md-3">
                                <label class="lang">Fecha Vencimiento Producto</label>
                            </div>
                            <div class="col-md-6">
                                <input class="calendario" type="text" id="fecha_vencimiento" name="fecha_vencimiento" style="width:100%" value="@Model.Fecha_Vencimiento_Producto" placeholder="---" readonly />
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

PedidosOnline/Views/Exportacion/ListaCertificadoCalidad.cshtml
@model PedidosOnline.Models.CertificadoCalidad
@{
    ViewBag.Title = "ListaCertificadoCalidad";
}
<style>
    a {
        color: #333;
    }
</style>
<script>

    $(document).ready(function () {
        $('tbl_certificado_calidad').dataTable({
            " processing": true,
            "bFilter": true,
            "bPaginate": true,
            "info": false,
            "bDestroy":true,
            aLengthMenu: [
            [15, 25, 50, 100, -1],
            [15, 25, 50, 100, "All"]
            ],
            "iDisplayLength": 15

        });

    });
</script>
<div class="panel">
    <div class="row">
        <div>
            <div class="nav">
                <span>
                    &nbsp;&nbsp;
                    <a href="@Url.Action("CertificadoCalidad", "Exportacion")" class="alink">
                        <i class="glyphicon glyphicon-plus"></i>&nbsp;<span class="lang" key="NUEVO">Nuevo</span>
                    </a>
                </span>
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <table id="tbl_certificado_calidad" class="table table-condensed table-striped table-bordered table-hover table-checkable table-responsive">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Producto</th>
                        <th>Codigo</th>
                        <th>Fecha revision</th>
                        <th>Cliente</th>
                        <th>Ciudad</th>
                        <th>Fecha elaboracion</th>
                        <th>Fecha Fecha Vencimiento</th>
                        <th>Cantidad</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (PedidosOnline.Models.CertificadoCalidad item in ViewBag.listadocalidad)
                    {
                        <tr>
                            <td>@item.RowID</td>
                            <td>@item.Item.Descripcion</td>
                            <td>@item.Codigo</td>
                            <td>@item.FechaRevision</td>
                            <td>@item.Cliente</td>
                            <td>@item.Ciudad.Nombre</td>
                            <td>@item.Fecha_Elaboracion_Producto</td>
                            <td>@item.Fecha_Vencimiento_Producto</td>
                            <td>@item.Cantidad</td>
                            <td><a href="@Url.Action("CertificadoCalidad", "Exportacion", new { RowID = item.RowID })"><i class="glyphicon glyphicon-pencil"></i></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
