PedidosOnline/Models/AgenteNaviera.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AgenteNaviera
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AgenteNaviera()
    {

        this.Calculadora = new HashSet<Calculadora>();

        this.Calculadora1 = new HashSet<Calculadora>();

        this.CalculadoraItems = new HashSet<CalculadoraItems>();

    }


    public int RowID { get; set; }

    public string Nombre { get; set; }

    public string UsuarioCreacion { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Calculadora> Calculadora { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Calculadora> Calculadora1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CalculadoraItems> CalculadoraItems { get; set; }

}

}

PedidosOnline/Models/Puerto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Puerto
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Puerto()
    {

        this.Proforma = new HashSet<Proforma>();

        this.Proforma1 = new HashSet<Proforma>();

    }


    public int RowID { get; set; }

    public string Nombre { get; set; }

    public Nullable<int> CiudadID { get; set; }

    public Nullable<System.DateTime> FechaCreacion { get; set; }

    public string UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public string UsuarioModificacion { get; set; }



    public virtual Ciudad Ciudad { get; set; }

    public virtual Ciudad Ciudad1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Proforma> Proforma { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Proforma> Proforma1 { get; set; }

}

}

PedidosOnline/Controllers/MaestroController.cs
using PedidosOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PedidosOnline.Controllers
{
    public class MaestroController : Controller
    {
        PedidosOnlineEntities db = new PedidosOnlineEntities();
        // GET: Maestro
        public ActionResult Index()
        {
            return View();
        }


        #region General
        private FormCollection DeSerialize(FormCollection formulario)
        {
            FormCollection collection = new FormCollection();
            //un-encode, and add spaces back in
            string querystring = Uri.UnescapeDataString(formulario["formulario"]).Replace("+", " ");
            var split = querystring.Split(new[] { '&' }, StringSplitOptions.RemoveEmptyEntries);
            Dictionary<string, string> items = new Dictionary<string, string>();
            foreach (string s in split)
            {
                string text = s.Substring(0, s.IndexOf("="));
                string value = s.Substring(s.IndexOf("=") + 1);

                if (items.Keys.Contains(text))
                    items[text] = items[text] + "," + value;
                else
                    items.Add(text, value);
            }
            foreach (var i in items)
            {
                collection.Add(i.Key, i.Value);
            }
            return collection;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion

        #region AgenteNaviera

        [CheckSessionOutAttribute]
        public ActionResult AgenteNaviera()
        {
            ViewBag.Agente = db.AgenteNaviera.ToList();
            return View();
        }


        [CheckSessionOutAttribute]
        public JsonResult GuardarAgente(FormCollection formulario)
        {
            String respuesta = "";
            formulario = DeSerialize(formulario);
            AgenteNaviera agente = new AgenteNaviera();
            try{
                    agente.Nombre = formulario["Nombre"];
                    agente.UsuarioCreacion = ((Usuario)Session["CurUser"]).NombreUsuario;
                agente.FechaCreacion = DateTime.Now;
                    db.AgenteNaviera.Add(agente);
                    db.SaveChanges();
                }
                catch (Exception ex)
                { return Json(new { respuesta = "Error " + ex.Message }); }
                respuesta = "Guardado Correctamente";
            
            return Json(respuesta);
        }

        public JsonResult RefrescarAgentes()
        {
            var data = (from agente in db.AgenteNaviera
                        select new
                        {
                            rowid = agente.RowID,
                            Nombre = agente.Nombre,
                            CreadoPor = agente.UsuarioCreacion,
                            ano = agente.FechaCreacion.Year,
                            mes = agente.FechaCreacion.Month,
                            dia = agente.FechaCreacion.Day


                        }).ToList();
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        [CheckSessionOutAttribute]
        public JsonResult ConsultarAgente(int RowID_Agente)
        {
            String respuesta = "";
            AgenteNaviera agente = new AgenteNaviera();

            try
            {
                agente = db.AgenteNaviera.Where(f => f.RowID == RowID_Agente).FirstOrDefault();
                respuesta = "ok";
            }
            catch (Exception ex)
            { return Json(new { agente = agente.Nombre }); }
            return Json(new {  nom = agente.Nombre, row_id_a= agente.RowID});
        }

        [CheckSessionOutAttribute]
        public JsonResult ActualizarAgente(FormCollection formulario, int RowID_Agente)
        {
            String respuesta = "";
            formulario = DeSerialize(formulario);
            AgenteNaviera agente = new AgenteNaviera();
            if (RowID_Agente != 0)
            {
                try
                {
                    agente = db.AgenteNaviera.Where(f => f.RowID == RowID_Agente).FirstOrDefault();
                    agente.Nombre = formulario["Nombre"];
                    agente.UsuarioModificacion = ((Usuario)Session["CurUser"]).NombreUsuario;
                    agente.FechaModificacion = DateTime.Now;
                    db.SaveChanges();
                }
                catch (Exception ex)
                { return Json(new { respuesta = "Error " + ex.Message }); }
                respuesta = "Guardado Correctamente";
            }
            return Json(respuesta);
        }
        #endregion

        #region Puerto

        [CheckSessionOutAttribute]
        public ActionResult Puerto(int? RowID_Lista)
        {
            if (RowID_Lista == null || RowID_Lista == 0)
            {
                ViewBag.Ciudad = db.Ciudad.ToList();
                ViewBag.Departamento = db.Departamento.ToList();
                ViewBag.Pais = db.Pais.ToList();
            }
            else {
                Puerto p = db.Puerto.Where(a => a.RowID == RowID_Lista).FirstOrDefault();
                ViewBag.Pais = db.Pais.ToList();
                ViewBag.Departamento = db.Departamento.Where(f=>f.PaisID==p.Ciudad.Departamento.PaisID);
                ViewBag.Ciudad = db.Ciudad.Where(f => f.DepartamentoID == p.Ciudad.DepartamentoID);
            }
         

            if (RowID_Lista != null)
            {
                return View(db.Puerto.Where(le => le.RowID == RowID_Lista).FirstOrDefault());
            }
            else
            {
                return View(new Puerto());
            }
        }

        [CheckSessionOutAttribute]
        public ActionResult ListadoPuerto()
        {
            ViewBag.Puerto = db.Puerto.ToList();
            return View();
        }


        [CheckSessionOutAttribute]
        public JsonResult CargarDepartamento(Int32 rowid)
        {
            List<Departamento> departamentos = db.Departamento.Where(f => f.PaisID == rowid).ToList();
            ///Para formar el Json
            var query = (from Departamento in departamentos
                         select new
                         {
                             RowId = Departamento.RowID,
                             Nombre = Departamento.Nombre
                         }
            ).ToList();

            return Json(query, JsonRequestBehavior.AllowGet);
        }

        [CheckSessionOutAttribute]
        public JsonResult CargarCiudad(Int32 rowid)
        {
            List<Ciudad> ciudad = db.Ciudad.Where(f => f.DepartamentoID == rowid).ToList();
            ///Para formar el Json
            var query = (from Ciudad in ciudad
                         select new
                         {
                             RowId = Ciudad.RowID,
                             Nombre = Ciudad.Nombre
                         }
            ).ToList();

            return Json(query, JsonRequestBehavior.AllowGet);
        }



        [CheckSessionOutAttribute]
        public JsonResult GuardarPuerto(FormCollection formulario, int? RowID_Puerto)
        {
            String respuesta = "";
            formulario = DeSerialize(formulario);
            if (RowID_Puerto == 0) { 
            Puerto puerto = new Puerto();
            try
            {
                puerto.Nombre = formulario["Nombre"];
                puerto.CiudadID = Convert.ToInt32(formulario["ciudad"]);
                puerto.UsuarioCreacion = "puerto";
                puerto.FechaCreacion = DateTime.Now;
                db.Puerto.Add(puerto);
                db.SaveChanges();
            }
            catch (Exception ex)
            { return Json(new { respuesta = "Error " + ex.Message }); }
            respuesta = "Guardado Correctamente";
        }else{
                Puerto puerto = db.Puerto.Where(f=> f.RowID == RowID_Puerto).FirstOrDefault();
                try
                {
                    puerto.Nombre = formulario["Nombre"];
                    puerto.CiudadID = Convert.ToInt32(formulario["ciudad"]);
                    puerto.UsuarioModificacion = Session["curUser"].ToString();
                    puerto.FechaModificacion = DateTime.Now;
                    db.SaveChanges();
                }
                catch (Exception ex)
                { return Json(new { respuesta = "Error " + ex.Message }); }
                respuesta = "Guardado Correctamente";
            }

            return Json(respuesta);
        }
        #endregion
        public ActionResult ListaUsuarioSistemas()
        {
            List<Usuario> lista_usuario = db.Usuario.Where(lius => lius.Activo == true).ToList();
            return View(lista_usuario);
        }
        public ActionResult CrearFirma(int? RowID_Usuario) {
            Usuario objUsuario = db.Usuario.Where(us => us.RowID == RowID_Usuario).FirstOrDefault();
            ViewBag.TipoFirma = db.Opcion.Where(o => o.Agrupacion.Nombre == "TIPOFIRMA").ToList();
            if (objUsuario == null) { 
                return View(new Usuario());
            }
            
            return View(objUsuario);
        }
        public JsonResult GuardarFirmaUsuario()
        {
            Firma objFirma = new Firma();
            HttpFileCollectionBase archivos;
             var tipo_firma = Request.Params["tipo_firma"].Split(',');
            var descripcion = Request.Params["descripcion"].Split(',');
            int contador_inser = 0;
            int rowid_usuario = int.Parse(Request.Params["rowid_usuario"]);

            //ViewBag.recursos = db.RecursosProforma.Where(rp => rp.RowID == rowid_proforma).ToList();

            string tipo_respuesta = "";
            string respuesta = "";
            string ruta_archivo;
            if (Request.Files.Count == 0)

PedidosOnline/Views/Maestro/ListaUsuarioSistemas.cshtml
@model List<PedidosOnline.Models.Usuario>
@{
    ViewBag.Title = "ListaUsuarioSistemas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    a {
        color: #333;
    }
</style>
<script>

    $(document).ready(function () {
        $('#table_usuarios').dataTable({
            " processing": true,
            "bFilter": true,
            "bPaginate": true,
            "info": false,
            "bDestroy":true,
            aLengthMenu: [
            [15, 25, 50, 100, -1],
            [15, 25, 50, 100, "All"]
            ],
            "iDisplayLength": 15

        });

    });
</script>
<div class="panel">
    <div class="row">
        <div>
            <div class="">
                <span>
                    &nbsp;&nbsp;
                    <a href="@Url.Action("ListaUsuarioSistemas", "Maestro")" class="alink">
                        <i class="glyphicon glyphicon-plus"></i>&nbsp;<span class="lang" key="NUEVO">Nuevo</span>
                    </a>
                </span>
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <table id="table_usuarios" class="table table-condensed table-striped table-bordered table-hover table-checkable table-responsive">
                <thead>
                    <tr>
                        <th></th>
                        <th></th>
                        <th>Nickname</th>
                        <th>Nombre usuario</th>
                        <th>Identificacion</th>
                        <th>Rol</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (PedidosOnline.Models.Usuario Usuario in Model)
                    {
                        <tr>
                            <td><a href="@Url.Action("CrearFirma", "Maestro", new { user = Usuario })"><i class="glyphicon glyphicon-search"></i></a></td>
                            <td>
                                <a onclick="modal_firma('@Usuario.RowID')" class="alink" ata-toggle="tooltip" data-placement="bottom" title="Exportar PDF">
                                    <i class="glyphicon glyphicon-file"></i>
                                </a>
                                @*<a href="@Url.Action("Export", "Proforma", new { @rowid = @cal.RowID, @rih = Request.Params["rih"] })"><i class="glyphicon glyphicon-export"></i></a>*@
                            </td>
                            <td>@Usuario.NombreUsuario</td>
                            <td>@Usuario.Tercero.RazonSocial</td>
                            <td>@Usuario.Tercero.Identificacion</td>
                            <td>@Usuario.Rol.Nombre</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div id="modal_firma"></div>
<script>
    function modal_firma(RowID) {
        var url = "CrearFirma?RowID_Usuario=" + RowID + "";
        $("#modal_firma").load(url.trim());
    }    
</script>

PedidosOnline/Views/Maestro/ListadoPuerto.cshtml
@model PedidosOnline.Models.Puerto
@{
    ViewBag.Title = "ListadoPuerto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    a {
        color: #333;
    }
</style>
<div class="panel">
    <div class="panel-heading">
        <div>
            <div class="nav">
                <span>
                    &nbsp;&nbsp;
                    <a href="@Url.Action("Puerto", "Maestro")" class="alink">
                        <i class="glyphicon glyphicon-plus"></i>&nbsp;<span class="lang" key="NUEVO">Nuevo</span>
                    </a>
                </span>
            </div>
        </div>
        @*<a class="btn btn-success" href='@Url.Action("Puerto", "Maestro")' style="float: right">+ Adicionar Puerto</a><br />*@

    </div>
    <div class="panel-body">
        <table id="demo-dt-basic" class="table table-striped table-bordered table-funcion">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Ciudad</th>
                    <th>Usuario creación</th>
                    <th>Fecha creación</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (PedidosOnline.Models.Puerto listaPuerto in ViewBag.Puerto)
                {
                    <tr>
                        <td>@listaPuerto.RowID</td>
                        <td>@listaPuerto.Nombre</td>
                        <td>@listaPuerto.Ciudad.Nombre</td>
                        <td>@listaPuerto.UsuarioCreacion</td>
                        <td>@listaPuerto.FechaCreacion</td>
                        <td><a href="@Url.Action("Puerto", "Maestro", new { RowID_Lista = listaPuerto.RowID })"><i class="glyphicon glyphicon-pencil"></i></a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

PedidosOnline/Views/Maestro/Puerto.cshtml
@model PedidosOnline.Models.Puerto
@{
    ViewBag.Title = "Puerto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    a {
        color: #333;
    }
</style>
<script>
    function valida_formulario() {
        debugger;
        hasChangue = false;
        var validator = $("#formulario_puerto").validate();
        if (validator.form()) {
            guardar_puerto();
        }
    }

    $(document).ready(function () {
        debugger;
        //CargarDepartamento();
        //CargarCiudad();
    })

</script>
<script>
    function guardar_puerto() {
        $.ajax({
            type: "POST",
            url: "/Maestro/GuardarPuerto",
            data: {
                formulario: $("#formulario_puerto").serialize(),
                RowID_Puerto: jQuery(".RowID_Puerto").val(),
            },

            success: function (data) {
                debugger;

                window.location = "/Maestro/ListadoPuerto"

            },
            error: function (data) {
                sweetAlert("", data.respuesta, "warning");
            }

        });
    }


    function CargarCiudad() {
        $.ajax({
            type: "POST",
            url: "/Maestro/CargarCiudad",
            data: {
                rowid: $("#departamento").val(),
            },
            success: function (data) {
                debugger;

                $("#ciudad").empty()
                $("#ciudad").append("<option disabled selected value='' >Seleccione una Opción</option>").trigger("chosen:updated");
                data.forEach(function (Ciudad) {
                        $("#ciudad").append("<option value='" + Ciudad.RowId + "' >" + Ciudad.Nombre
                        + "</option>").trigger("chosen:updated");
                        $("#ciudad").trigger("chosen:updated");
                  });
            },
            error: function (data) {
                swal("ERROR", data, "error");
            }
        });
    }

    function CargarDepartamento() {
        debugger;
        $.ajax({
            type: "POST",
            url: "/Maestro/CargarDepartamento",
            data: {
                rowid: $("#pais").val(),
            },
            success: function (data) {
                $("#departamento").empty()
                $("#departamento").append("<option disabled selected value='' >Seleccione una Opción</option>").trigger("chosen:updated");
                data.forEach(function (Departamento) {
                       $("#departamento").append("<option value='" + Departamento.RowId + "' >" + Departamento.Nombre
                       +"</option>").trigger("chosen:updated");
                        $("#departamento").trigger("chosen:updated");
                });
            },
            error: function (data) {
                swal("ERROR", data, "error");
            }
        });
    }
</script>


<div class="panel">

    <div class="row" id="div_menu" style="margin-bottom:20px">
        <div class="col-md-12">
            <div class="nav">
                <span>
                    &nbsp;&nbsp;
                    <a href="@Url.Action("ListadoPuerto","Maestro",new {  @rih = Request.Params["rih"] })" class="alink">
                        <i class="glyphicon glyphicon-list-alt"></i>&nbsp;<span class="lang" key="VISTA">Vista&nbsp;&nbsp;</span>
                    </a>
                </span>
                <span>
                    <a href="javascript:valida_formulario();" class="alink">
                        <i class="glyphicon glyphicon-floppy-disk"></i>&nbsp;<span class="lang" key="GUARDAR">Guardar</span>
                    </a>
                </span>
                <span>
                    &nbsp;&nbsp;
                    <a href="javascript:valida_formulario();" class="alink">
                        <i class="glyphicon glyphicon-floppy-disk"></i><span class="lang" key="GUARDAR_&_CERRAR">&nbsp;Guardar&nbsp;&&nbsp;Cerrar</span>
                    </a>
                </span>
            </div>
        </div>
    </div>
    <div class="tabbable tabbable-custom tabs-top">
        <ul class="nav nav-tabs tabs-top">
            <li id="li_tab1" class="active"><a href="#tab1" data-toggle="tab">Datos generales</a></li>
        </ul>
    </div>



    <div class="tab-content" style="overflow:hidden">
        <div class="col-md-12">

            <form id="formulario_puerto" data-toggle="validator" role="form">
                <input type="hidden" class="RowID_Puerto" name="RowID_Puerto" value="@Model.RowID" />
                <input type="hidden" class="RowID_Detalle" name="RowID_Detalle" />
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label class="control-label">*Nombre:</label>
                                <input name="nombre" id="nombre" class="form-control" value="@Model.Nombre" required>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label class="control-label">*País:</label>
                                <select name="pais" id="pais" class="chosen form-control" required onchange="javascript:CargarDepartamento()">
                                    <option value="" disabled selected>Seleccione una opcion</option>
                                    @foreach (PedidosOnline.Models.Pais pais in ViewBag.Pais)
                                    {

                                        if (Model.RowID != 0 && @Model.Ciudad.Departamento.PaisID != null && @Model.Ciudad.Departamento.PaisID.Equals(@pais.RowID))
                                        {
                                            <option value="@pais.RowID" selected>@pais.Nombre</option>
                                        }
                                        else
                                        {
                                            <option value="@pais.RowID">@pais.Nombre</option>
                                        }
                                    }
                                </select>

                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label class="control-label">*Departamento:</label>
                                <select name="departamento" id="departamento" class="chosen form-control" onchange="javascript:CargarCiudad()" required>
                                    <option value="" disabled selected>Seleccione una opcion</option>
                                    @foreach (PedidosOnline.Models.Departamento departamento in ViewBag.Departamento)
                                    {
                                        if (Model.RowID != 0 && @Model.Ciudad.DepartamentoID != null && @Model.Ciudad.DepartamentoID.Equals(@departamento.RowID))
                                        {
                                            <option value="@departamento.RowID" selected>@departamento.Nombre</option>

                                        }
                                        else
                                        {
                                            <option value="@departamento.RowID">@departamento.Nombre</option>


                                        }

                                    }
                                </select>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <div class="form-group">
                                <label class="control-label">*Ciudad:</label>
                                <select name="ciudad" id="ciudad" class="chosen form-control" required>
                                    <option value="" disabled selected>Seleccione una opcion</option>
                                    @foreach (PedidosOnline.Models.Ciudad ciudad in ViewBag.Ciudad)
                                    {
                                        if (Model.RowID != 0 && @Model.CiudadID != null && @Model.CiudadID.Equals(@ciudad.RowID))
                                        {
                                            <option value="@ciudad.RowID" selected>@ciudad.Nombre</option>

                                        }
                                        else
                                        {
                                            <option value="@ciudad.RowID">@ciudad.Nombre</option>
                                        }
                                    }
                                </select>
                            </div>
                        </div>


                    </div>
                    @*@if (Model.RowID == 0)
                        {


                            <button type="submit" class="btn btn-success" onclick="javascript:valida_formulario()" style="float: right;  width:100px">
                                <i class="glyphicon glyphicon-ok"></i>  Guardar
                            </button>
                        }
                        else
                        {
                            <button type="submit" class="btn btn-success" onclick="javascript:valida_formulario()" style="float: right;  width:100px">
                                <i class="glyphicon glyphicon-floppy-disk"></i>  Actualizar
                            </button>
                        }*@
                </div>

            </form>
        </div>
    </div>
        </div>